/* WARNING ! WARNING *** THIS FILE IS GENERATED BY C2J !!!

   DO NOT MAKE ANY CHANGES *** MAKE CHANGES IN THE SKELETON FILES !!!
*/


/**
 * @(#) GLUFunc.java
 */


package gl4java;

/**
 * The base interface for GLU native function mapping
 *
 * @version 	2.00, 21. April 1999
 * @author      Sven Goethel
 */
public interface GLUFunc 
	extends GLUEnum 
{

public String gluErrorString ( int errorCode ) ;

public String gluGetString ( int name ) ;

public String getNativeVendor ( ) ;
public String getNativeVersion ( ) ;

public String getClassVendor ( )  ;
public String getClassVersion ( ) ;

public long gluNewQuadric( );
public long gluNewNurbsRenderer( );
public long gluNewTess( );

public void  gluQuadricCallback(
                                  long qobj, int which,
			          Object methodClassInstance, 
				  String methodName, 
				  String signature
				  );

public void  gluNurbsCallback(
			          long nobj, int which,
			          Object methodClassInstance, 
			          String methodName, 
				  String signature
				  );


public void  gluTessCallback(
				  long tobj, int which,
			          Object methodClassInstance, 
			          String methodName, 
				  String signature,
				  int voidArrayLen1,
				  int voidArrayLen2,
				  int voidArrayLen3,
				  int voidArrayLen4,
				  int voidArrayLen5
				  );

public void  gluDeleteQuadric( long qobj );

public void  gluDeleteNurbsRenderer( long nobj );

public void  gluDeleteTess( long tobj );

/**
 * C2J Parser Version 1.5 Beta
 * Jausoft - Sven Goethel Software Development
 * Reading from file: glu-proto-auto.orig.h . . .
 * Destination-Class: gl4java_GLUFuncJauJNI ! 
 */

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluLookAt ( GLdouble eyex , GLdouble eyey , GLdouble eyez , GLdouble centerx , GLdouble centery , GLdouble centerz , GLdouble upx , GLdouble upy , GLdouble upz ) ;
 * </pre> 
 */
	public void gluLookAt (
		double eyex,
		double eyey,
		double eyez,
		double centerx,
		double centery,
		double centerz,
		double upx,
		double upy,
		double upz
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluOrtho2D ( GLdouble left , GLdouble right , GLdouble bottom , GLdouble top ) ;
 * </pre> 
 */
	public void gluOrtho2D (
		double left,
		double right,
		double bottom,
		double top
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluPerspective ( GLdouble fovy , GLdouble aspect , GLdouble zNear , GLdouble zFar ) ;
 * </pre> 
 */
	public void gluPerspective (
		double fovy,
		double aspect,
		double zNear,
		double zFar
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluPickMatrix ( GLdouble x , GLdouble y , GLdouble width , GLdouble height , GLint * viewport ) ;
 * </pre> 
 */
	public void gluPickMatrix (
		double x,
		double y,
		double width,
		double height,
		int[] viewport
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern GLint gluProject ( GLdouble objx , GLdouble objy , GLdouble objz , const GLdouble modelMatrix [ 16 ] , const GLdouble projMatrix [ 16 ] , const GLint viewport [ 4 ] , GLdouble * winx , GLdouble * winy , GLdouble * winz ) ;
 * </pre> 
 */
	public int gluProject (
		double objx,
		double objy,
		double objz,
		double[] modelMatrix,
		double[] projMatrix,
		int[] viewport,
		double[] winx,
		double[] winy,
		double[] winz
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern GLint gluUnProject ( GLdouble winx , GLdouble winy , GLdouble winz , const GLdouble modelMatrix [ 16 ] , const GLdouble projMatrix [ 16 ] , const GLint viewport [ 4 ] , GLdouble * objx , GLdouble * objy , GLdouble * objz ) ;
 * </pre> 
 */
	public int gluUnProject (
		double winx,
		double winy,
		double winz,
		double[] modelMatrix,
		double[] projMatrix,
		int[] viewport,
		double[] objx,
		double[] objy,
		double[] objz
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern GLint gluScaleImage ( GLenum format , GLsizei widthin , GLsizei heightin , GLenum typein , const char * datain , GLsizei widthout , GLsizei heightout , GLenum typeout , char * dataout ) ;
 * </pre> 
 */
	public int gluScaleImage (
		int format,
		int widthin,
		int heightin,
		int typein,
		byte[] datain,
		int widthout,
		int heightout,
		int typeout,
		byte[] dataout
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern GLint gluBuild1DMipmaps ( GLenum target , GLint components , GLint width , GLenum format , GLenum type , const void * data ) ;
 * </pre> 
 */
	public int gluBuild1DMipmaps (
		int target,
		int components,
		int width,
		int format,
		int type,
		byte[] data
	) ;
	public int gluBuild1DMipmaps (
		int target,
		int components,
		int width,
		int format,
		int type,
		short[] data
	) ;
	public int gluBuild1DMipmaps (
		int target,
		int components,
		int width,
		int format,
		int type,
		int[] data
	) ;
	public int gluBuild1DMipmaps (
		int target,
		int components,
		int width,
		int format,
		int type,
		float[] data
	) ;
	public int gluBuild1DMipmaps (
		int target,
		int components,
		int width,
		int format,
		int type,
		double[] data
	) ;
	public int gluBuild1DMipmaps (
		int target,
		int components,
		int width,
		int format,
		int type,
		boolean[] data
	) ;
	public int gluBuild1DMipmaps (
		int target,
		int components,
		int width,
		int format,
		int type,
		long[] data
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern GLint gluBuild2DMipmaps ( GLenum target , GLint components , GLint width , GLint height , GLenum format , GLenum type , const void * data ) ;
 * </pre> 
 */
	public int gluBuild2DMipmaps (
		int target,
		int components,
		int width,
		int height,
		int format,
		int type,
		byte[] data
	) ;
	public int gluBuild2DMipmaps (
		int target,
		int components,
		int width,
		int height,
		int format,
		int type,
		short[] data
	) ;
	public int gluBuild2DMipmaps (
		int target,
		int components,
		int width,
		int height,
		int format,
		int type,
		int[] data
	) ;
	public int gluBuild2DMipmaps (
		int target,
		int components,
		int width,
		int height,
		int format,
		int type,
		float[] data
	) ;
	public int gluBuild2DMipmaps (
		int target,
		int components,
		int width,
		int height,
		int format,
		int type,
		double[] data
	) ;
	public int gluBuild2DMipmaps (
		int target,
		int components,
		int width,
		int height,
		int format,
		int type,
		boolean[] data
	) ;
	public int gluBuild2DMipmaps (
		int target,
		int components,
		int width,
		int height,
		int format,
		int type,
		long[] data
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluQuadricDrawStyle ( GLUquadricObj * quadObject , GLenum drawStyle ) ;
 * </pre> 
 */
	public void gluQuadricDrawStyle (
		long quadObject,
		int drawStyle
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluQuadricOrientation ( GLUquadricObj * quadObject , GLenum orientation ) ;
 * </pre> 
 */
	public void gluQuadricOrientation (
		long quadObject,
		int orientation
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluQuadricNormals ( GLUquadricObj * quadObject , GLenum normals ) ;
 * </pre> 
 */
	public void gluQuadricNormals (
		long quadObject,
		int normals
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluQuadricTexture ( GLUquadricObj * quadObject , GLboolean textureCoords ) ;
 * </pre> 
 */
	public void gluQuadricTexture (
		long quadObject,
		boolean textureCoords
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluCylinder ( GLUquadricObj * qobj , GLdouble baseRadius , GLdouble topRadius , GLdouble height , GLint slices , GLint stacks ) ;
 * </pre> 
 */
	public void gluCylinder (
		long qobj,
		double baseRadius,
		double topRadius,
		double height,
		int slices,
		int stacks
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluSphere ( GLUquadricObj * qobj , GLdouble radius , GLint slices , GLint stacks ) ;
 * </pre> 
 */
	public void gluSphere (
		long qobj,
		double radius,
		int slices,
		int stacks
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluDisk ( GLUquadricObj * qobj , GLdouble innerRadius , GLdouble outerRadius , GLint slices , GLint loops ) ;
 * </pre> 
 */
	public void gluDisk (
		long qobj,
		double innerRadius,
		double outerRadius,
		int slices,
		int loops
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluPartialDisk ( GLUquadricObj * qobj , GLdouble innerRadius , GLdouble outerRadius , GLint slices , GLint loops , GLdouble startAngle , GLdouble sweepAngle ) ;
 * </pre> 
 */
	public void gluPartialDisk (
		long qobj,
		double innerRadius,
		double outerRadius,
		int slices,
		int loops,
		double startAngle,
		double sweepAngle
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluLoadSamplingMatrices ( GLUnurbsObj * nobj , const GLfloat modelMatrix [ 16 ] , const GLfloat projMatrix [ 16 ] , const GLint viewport [ 4 ] ) ;
 * </pre> 
 */
	public void gluLoadSamplingMatrices (
		long nobj,
		float[] modelMatrix,
		float[] projMatrix,
		int[] viewport
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluNurbsProperty ( GLUnurbsObj * nobj , GLenum property , GLfloat value ) ;
 * </pre> 
 */
	public void gluNurbsProperty (
		long nobj,
		int property,
		float value
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluGetNurbsProperty ( GLUnurbsObj * nobj , GLenum property , GLfloat * value ) ;
 * </pre> 
 */
	public void gluGetNurbsProperty (
		long nobj,
		int property,
		float[] value
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluBeginCurve ( GLUnurbsObj * nobj ) ;
 * </pre> 
 */
	public void gluBeginCurve (
		long nobj
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluEndCurve ( GLUnurbsObj * nobj ) ;
 * </pre> 
 */
	public void gluEndCurve (
		long nobj
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluNurbsCurve ( GLUnurbsObj * nobj , GLint nknots , GLfloat * knot , GLint stride , GLfloat * ctlarray , GLint order , GLenum type ) ;
 * </pre> 
 */
	public void gluNurbsCurve (
		long nobj,
		int nknots,
		float[] knot,
		int stride,
		float[] ctlarray,
		int order,
		int type
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluBeginSurface ( GLUnurbsObj * nobj ) ;
 * </pre> 
 */
	public void gluBeginSurface (
		long nobj
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluEndSurface ( GLUnurbsObj * nobj ) ;
 * </pre> 
 */
	public void gluEndSurface (
		long nobj
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluNurbsSurface ( GLUnurbsObj * nobj , GLint sknot_count , GLfloat * sknot , GLint tknot_count , GLfloat * tknot , GLint s_stride , GLint t_stride , GLfloat * ctlarray , GLint sorder , GLint torder , GLenum type ) ;
 * </pre> 
 */
	public void gluNurbsSurface (
		long nobj,
		int sknot_count,
		float[] sknot,
		int tknot_count,
		float[] tknot,
		int s_stride,
		int t_stride,
		float[] ctlarray,
		int sorder,
		int torder,
		int type
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluBeginTrim ( GLUnurbsObj * nobj ) ;
 * </pre> 
 */
	public void gluBeginTrim (
		long nobj
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluEndTrim ( GLUnurbsObj * nobj ) ;
 * </pre> 
 */
	public void gluEndTrim (
		long nobj
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluPwlCurve ( GLUnurbsObj * nobj , GLint count , GLfloat * array , GLint stride , GLenum type ) ;
 * </pre> 
 */
	public void gluPwlCurve (
		long nobj,
		int count,
		float[] array,
		int stride,
		int type
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluTessBeginPolygon ( GLUtesselator * tobj , void * polygon_data ) ;
 * </pre> 
 */
	public void gluTessBeginPolygon (
		long tobj,
		byte[] polygon_data
	) ;
	public void gluTessBeginPolygon (
		long tobj,
		short[] polygon_data
	) ;
	public void gluTessBeginPolygon (
		long tobj,
		int[] polygon_data
	) ;
	public void gluTessBeginPolygon (
		long tobj,
		float[] polygon_data
	) ;
	public void gluTessBeginPolygon (
		long tobj,
		double[] polygon_data
	) ;
	public void gluTessBeginPolygon (
		long tobj,
		boolean[] polygon_data
	) ;
	public void gluTessBeginPolygon (
		long tobj,
		long[] polygon_data
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluTessBeginContour ( GLUtesselator * tobj ) ;
 * </pre> 
 */
	public void gluTessBeginContour (
		long tobj
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluTessVertex ( GLUtesselator * tobj , GLdouble coords [ 3 ] , void * vertex_data ) ;
 * </pre> 
 */
	public void gluTessVertex (
		long tobj,
		double[] coords,
		byte[] vertex_data
	) ;
	public void gluTessVertex (
		long tobj,
		double[] coords,
		short[] vertex_data
	) ;
	public void gluTessVertex (
		long tobj,
		double[] coords,
		int[] vertex_data
	) ;
	public void gluTessVertex (
		long tobj,
		double[] coords,
		float[] vertex_data
	) ;
	public void gluTessVertex (
		long tobj,
		double[] coords,
		double[] vertex_data
	) ;
	public void gluTessVertex (
		long tobj,
		double[] coords,
		boolean[] vertex_data
	) ;
	public void gluTessVertex (
		long tobj,
		double[] coords,
		long[] vertex_data
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluTessEndContour ( GLUtesselator * tobj ) ;
 * </pre> 
 */
	public void gluTessEndContour (
		long tobj
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluTessEndPolygon ( GLUtesselator * tobj ) ;
 * </pre> 
 */
	public void gluTessEndPolygon (
		long tobj
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluTessProperty ( GLUtesselator * tobj , GLenum which , GLdouble value ) ;
 * </pre> 
 */
	public void gluTessProperty (
		long tobj,
		int which,
		double value
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluTessNormal ( GLUtesselator * tobj , GLdouble x , GLdouble y , GLdouble z ) ;
 * </pre> 
 */
	public void gluTessNormal (
		long tobj,
		double x,
		double y,
		double z
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluGetTessProperty ( GLUtesselator * tobj , GLenum which , GLdouble * value ) ;
 * </pre> 
 */
	public void gluGetTessProperty (
		long tobj,
		int which,
		double[] value
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluBeginPolygon ( GLUtesselator * tobj ) ;
 * </pre> 
 */
	public void gluBeginPolygon (
		long tobj
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluNextContour ( GLUtesselator * tobj , GLenum type ) ;
 * </pre> 
 */
	public void gluNextContour (
		long tobj,
		int type
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluEndPolygon ( GLUtesselator * tobj ) ;
 * </pre> 
 */
	public void gluEndPolygon (
		long tobj
	) ;

/* C2J Parser Version 1.5 Beta:  Java program parsed successfully. */ 


}

