/* WARNING ! WARNING *** THIS FILE IS GENERATED BY C2J !!!

   DO NOT MAKE ANY CHANGES *** MAKE CHANGES IN THE SKELETON FILES !!!
*/


/**
 * @(#) GLUFunc.java
 */


package gl4java;

/**
 * The base interface for GLU native function mapping
 *
 * @version 	2.00, 21. April 1999
 * @author      Sven Goethel
 */
public interface GLUFunc 
	extends GLUEnum 
{


public String gluErrorString ( int errorCode ) ;

public String gluGetString ( int name ) ;

public String getNativeVendor ( ) ;
public String getNativeVersion ( ) ;

public String getClassVendor ( )  ;
public String getClassVersion ( ) ;

public long gluNewQuadric( );
public long gluNewNurbsRenderer( );
public long gluNewTess( );

public void  gluQuadricCallback(
                                  long qobj, int which,
			          Object methodClassInstance, 
				  String methodName, 
				  String signature
				  );

public void  gluNurbsCallback(
			          long nobj, int which,
			          Object methodClassInstance, 
			          String methodName, 
				  String signature
				  );


public void  gluTessCallback(
				  long tobj, int which,
			          Object methodClassInstance, 
			          String methodName, 
				  String signature,
				  int voidArrayLen1,
				  int voidArrayLen2,
				  int voidArrayLen3,
				  int voidArrayLen4,
				  int voidArrayLen5
				  );

public void  gluDeleteQuadric( long qobj );

public void  gluDeleteNurbsRenderer( long nobj );

public void  gluDeleteTess( long tobj );

/**
 * Wrapper for original gluProject,
 * where the orig. last three arguments are wrapped 
 * mapped in one array: (winx[1], winy[1], winz[1]) <-> win[3]
 *
 * @param obj array of the three obj x,y,z input components
 * @param win array of the three win x,y,z output components
 * @see gl4java.GLUFunc#gluProject
 */
public int gluProject(double obj[],
                      double[] modelMatrix,
                      double[] projMatrix,
                      int[] viewport,
                      double[] win);

/**
 * Wrapper for original gluProject,
 * where the orig. last three arguments are wrapped 
 * mapped in one array: (winx[1], winy[1], winz[1]) <-> win[3]
 *
 * @param win array of the three win x,y,z output components
 * @see gl4java.GLUFunc#gluProject
 */
public int gluProject(double objx,
                      double objy,
                      double objz,
                      double[] modelMatrix,
                      double[] projMatrix,
                      int[] viewport,
                      double[] win);

/**
 * Wrapper for original gluUnProject,
 * where the orig. last three arguments are wrapped 
 * mapped in one array: (objx[1], objy[1], objz[1]) <-> obj[3]
 *
 * @param win array of the three win x,y,z input components
 * @param obj array of the three obj x,y,z output components
 * @see gl4java.GLUFunc#gluUnProject
 */
public int gluUnProject(double win[],
                        double[] modelMatrix,
                        double[] projMatrix,
                        int[] viewport,
                        double[] obj);

/**
 * Wrapper for original gluUnProject,
 * where the orig. last three arguments are wrapped 
 * mapped in one array: (objx[1], objy[1], objz[1]) <-> obj[3]
 *
 * @param obj array of the three obj x,y,z output components
 * @see gl4java.GLUFunc#gluUnProject
 */
public int gluUnProject(double winx,
                        double winy,
                        double winz,
                        double[] modelMatrix,
                        double[] projMatrix,
                        int[] viewport,
                        double[] obj);


/**
 * C2J Parser Version 3.0
 * Jausoft - Sven Goethel Software Development
 * Reading from file: glu-proto-auto.orig.h . . .
 * Destination-Class: gl4java_GLUFuncJauJNI ! 
 */

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluBeginCurve ( GLUnurbs * nurb ) ;
 * </pre> 
 */
	public void gluBeginCurve (
		long nurb
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluBeginPolygon ( GLUtesselator * tess ) ;
 * </pre> 
 */
	public void gluBeginPolygon (
		long tess
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluBeginSurface ( GLUnurbs * nurb ) ;
 * </pre> 
 */
	public void gluBeginSurface (
		long nurb
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluBeginTrim ( GLUnurbs * nurb ) ;
 * </pre> 
 */
	public void gluBeginTrim (
		long nurb
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern GLint gluBuild1DMipmapLevels ( GLenum target , GLint internalFormat , GLsizei width , GLenum format , GLenum type , GLint level , GLint base , GLint max , const void * data ) ;
 * </pre> 
 */
	public int gluBuild1DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int format,
		int type,
		int level,
		int base,
		int max,
		byte[] data
	) ;
	public int gluBuild1DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int format,
		int type,
		int level,
		int base,
		int max,
		short[] data
	) ;
	public int gluBuild1DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int format,
		int type,
		int level,
		int base,
		int max,
		int[] data
	) ;
	public int gluBuild1DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int format,
		int type,
		int level,
		int base,
		int max,
		float[] data
	) ;
	public int gluBuild1DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int format,
		int type,
		int level,
		int base,
		int max,
		double[] data
	) ;
	public int gluBuild1DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int format,
		int type,
		int level,
		int base,
		int max,
		boolean[] data
	) ;
	public int gluBuild1DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int format,
		int type,
		int level,
		int base,
		int max,
		long[] data
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern GLint gluBuild1DMipmaps ( GLenum target , GLint internalFormat , GLsizei width , GLenum format , GLenum type , const void * data ) ;
 * </pre> 
 */
	public int gluBuild1DMipmaps (
		int target,
		int internalFormat,
		int width,
		int format,
		int type,
		byte[] data
	) ;
	public int gluBuild1DMipmaps (
		int target,
		int internalFormat,
		int width,
		int format,
		int type,
		short[] data
	) ;
	public int gluBuild1DMipmaps (
		int target,
		int internalFormat,
		int width,
		int format,
		int type,
		int[] data
	) ;
	public int gluBuild1DMipmaps (
		int target,
		int internalFormat,
		int width,
		int format,
		int type,
		float[] data
	) ;
	public int gluBuild1DMipmaps (
		int target,
		int internalFormat,
		int width,
		int format,
		int type,
		double[] data
	) ;
	public int gluBuild1DMipmaps (
		int target,
		int internalFormat,
		int width,
		int format,
		int type,
		boolean[] data
	) ;
	public int gluBuild1DMipmaps (
		int target,
		int internalFormat,
		int width,
		int format,
		int type,
		long[] data
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern GLint gluBuild2DMipmapLevels ( GLenum target , GLint internalFormat , GLsizei width , GLsizei height , GLenum format , GLenum type , GLint level , GLint base , GLint max , const void * data ) ;
 * </pre> 
 */
	public int gluBuild2DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int height,
		int format,
		int type,
		int level,
		int base,
		int max,
		byte[] data
	) ;
	public int gluBuild2DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int height,
		int format,
		int type,
		int level,
		int base,
		int max,
		short[] data
	) ;
	public int gluBuild2DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int height,
		int format,
		int type,
		int level,
		int base,
		int max,
		int[] data
	) ;
	public int gluBuild2DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int height,
		int format,
		int type,
		int level,
		int base,
		int max,
		float[] data
	) ;
	public int gluBuild2DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int height,
		int format,
		int type,
		int level,
		int base,
		int max,
		double[] data
	) ;
	public int gluBuild2DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int height,
		int format,
		int type,
		int level,
		int base,
		int max,
		boolean[] data
	) ;
	public int gluBuild2DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int height,
		int format,
		int type,
		int level,
		int base,
		int max,
		long[] data
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern GLint gluBuild2DMipmaps ( GLenum target , GLint internalFormat , GLsizei width , GLsizei height , GLenum format , GLenum type , const void * data ) ;
 * </pre> 
 */
	public int gluBuild2DMipmaps (
		int target,
		int internalFormat,
		int width,
		int height,
		int format,
		int type,
		byte[] data
	) ;
	public int gluBuild2DMipmaps (
		int target,
		int internalFormat,
		int width,
		int height,
		int format,
		int type,
		short[] data
	) ;
	public int gluBuild2DMipmaps (
		int target,
		int internalFormat,
		int width,
		int height,
		int format,
		int type,
		int[] data
	) ;
	public int gluBuild2DMipmaps (
		int target,
		int internalFormat,
		int width,
		int height,
		int format,
		int type,
		float[] data
	) ;
	public int gluBuild2DMipmaps (
		int target,
		int internalFormat,
		int width,
		int height,
		int format,
		int type,
		double[] data
	) ;
	public int gluBuild2DMipmaps (
		int target,
		int internalFormat,
		int width,
		int height,
		int format,
		int type,
		boolean[] data
	) ;
	public int gluBuild2DMipmaps (
		int target,
		int internalFormat,
		int width,
		int height,
		int format,
		int type,
		long[] data
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern GLint gluBuild3DMipmapLevels ( GLenum target , GLint internalFormat , GLsizei width , GLsizei height , GLsizei depth , GLenum format , GLenum type , GLint level , GLint base , GLint max , const void * data ) ;
 * </pre> 
 */
	public int gluBuild3DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int height,
		int depth,
		int format,
		int type,
		int level,
		int base,
		int max,
		byte[] data
	) ;
	public int gluBuild3DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int height,
		int depth,
		int format,
		int type,
		int level,
		int base,
		int max,
		short[] data
	) ;
	public int gluBuild3DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int height,
		int depth,
		int format,
		int type,
		int level,
		int base,
		int max,
		int[] data
	) ;
	public int gluBuild3DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int height,
		int depth,
		int format,
		int type,
		int level,
		int base,
		int max,
		float[] data
	) ;
	public int gluBuild3DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int height,
		int depth,
		int format,
		int type,
		int level,
		int base,
		int max,
		double[] data
	) ;
	public int gluBuild3DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int height,
		int depth,
		int format,
		int type,
		int level,
		int base,
		int max,
		boolean[] data
	) ;
	public int gluBuild3DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int height,
		int depth,
		int format,
		int type,
		int level,
		int base,
		int max,
		long[] data
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern GLint gluBuild3DMipmaps ( GLenum target , GLint internalFormat , GLsizei width , GLsizei height , GLsizei depth , GLenum format , GLenum type , const void * data ) ;
 * </pre> 
 */
	public int gluBuild3DMipmaps (
		int target,
		int internalFormat,
		int width,
		int height,
		int depth,
		int format,
		int type,
		byte[] data
	) ;
	public int gluBuild3DMipmaps (
		int target,
		int internalFormat,
		int width,
		int height,
		int depth,
		int format,
		int type,
		short[] data
	) ;
	public int gluBuild3DMipmaps (
		int target,
		int internalFormat,
		int width,
		int height,
		int depth,
		int format,
		int type,
		int[] data
	) ;
	public int gluBuild3DMipmaps (
		int target,
		int internalFormat,
		int width,
		int height,
		int depth,
		int format,
		int type,
		float[] data
	) ;
	public int gluBuild3DMipmaps (
		int target,
		int internalFormat,
		int width,
		int height,
		int depth,
		int format,
		int type,
		double[] data
	) ;
	public int gluBuild3DMipmaps (
		int target,
		int internalFormat,
		int width,
		int height,
		int depth,
		int format,
		int type,
		boolean[] data
	) ;
	public int gluBuild3DMipmaps (
		int target,
		int internalFormat,
		int width,
		int height,
		int depth,
		int format,
		int type,
		long[] data
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern GLboolean gluCheckExtension ( const GLubyte * extName , const GLubyte * extString ) ;
 * </pre> 
 */
	public boolean gluCheckExtension (
		byte[] extName,
		byte[] extString
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluCylinder ( GLUquadric * quad , GLdouble base , GLdouble top , GLdouble height , GLint slices , GLint stacks ) ;
 * </pre> 
 */
	public void gluCylinder (
		long quad,
		double base,
		double top,
		double height,
		int slices,
		int stacks
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluDisk ( GLUquadric * quad , GLdouble inner , GLdouble outer , GLint slices , GLint loops ) ;
 * </pre> 
 */
	public void gluDisk (
		long quad,
		double inner,
		double outer,
		int slices,
		int loops
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluEndCurve ( GLUnurbs * nurb ) ;
 * </pre> 
 */
	public void gluEndCurve (
		long nurb
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluEndPolygon ( GLUtesselator * tess ) ;
 * </pre> 
 */
	public void gluEndPolygon (
		long tess
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluEndSurface ( GLUnurbs * nurb ) ;
 * </pre> 
 */
	public void gluEndSurface (
		long nurb
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluEndTrim ( GLUnurbs * nurb ) ;
 * </pre> 
 */
	public void gluEndTrim (
		long nurb
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluGetNurbsProperty ( GLUnurbs * nurb , GLenum property , GLfloat * data ) ;
 * </pre> 
 */
	public void gluGetNurbsProperty (
		long nurb,
		int property,
		float[] data
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluGetTessProperty ( GLUtesselator * tess , GLenum which , GLdouble * data ) ;
 * </pre> 
 */
	public void gluGetTessProperty (
		long tess,
		int which,
		double[] data
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluLoadSamplingMatrices ( GLUnurbs * nurb , const GLfloat * model , const GLfloat * perspective , const GLint * view ) ;
 * </pre> 
 */
	public void gluLoadSamplingMatrices (
		long nurb,
		float[] model,
		float[] perspective,
		int[] view
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluLookAt ( GLdouble eyeX , GLdouble eyeY , GLdouble eyeZ , GLdouble centerX , GLdouble centerY , GLdouble centerZ , GLdouble upX , GLdouble upY , GLdouble upZ ) ;
 * </pre> 
 */
	public void gluLookAt (
		double eyeX,
		double eyeY,
		double eyeZ,
		double centerX,
		double centerY,
		double centerZ,
		double upX,
		double upY,
		double upZ
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluNextContour ( GLUtesselator * tess , GLenum type ) ;
 * </pre> 
 */
	public void gluNextContour (
		long tess,
		int type
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluNurbsCurve ( GLUnurbs * nurb , GLint knotCount , GLfloat * knots , GLint stride , GLfloat * control , GLint order , GLenum type ) ;
 * </pre> 
 */
	public void gluNurbsCurve (
		long nurb,
		int knotCount,
		float[] knots,
		int stride,
		float[] control,
		int order,
		int type
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluNurbsProperty ( GLUnurbs * nurb , GLenum property , GLfloat value ) ;
 * </pre> 
 */
	public void gluNurbsProperty (
		long nurb,
		int property,
		float value
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluNurbsSurface ( GLUnurbs * nurb , GLint sKnotCount , GLfloat * sKnots , GLint tKnotCount , GLfloat * tKnots , GLint sStride , GLint tStride , GLfloat * control , GLint sOrder , GLint tOrder , GLenum type ) ;
 * </pre> 
 */
	public void gluNurbsSurface (
		long nurb,
		int sKnotCount,
		float[] sKnots,
		int tKnotCount,
		float[] tKnots,
		int sStride,
		int tStride,
		float[] control,
		int sOrder,
		int tOrder,
		int type
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluOrtho2D ( GLdouble left , GLdouble right , GLdouble bottom , GLdouble top ) ;
 * </pre> 
 */
	public void gluOrtho2D (
		double left,
		double right,
		double bottom,
		double top
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluPartialDisk ( GLUquadric * quad , GLdouble inner , GLdouble outer , GLint slices , GLint loops , GLdouble start , GLdouble sweep ) ;
 * </pre> 
 */
	public void gluPartialDisk (
		long quad,
		double inner,
		double outer,
		int slices,
		int loops,
		double start,
		double sweep
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluPerspective ( GLdouble fovy , GLdouble aspect , GLdouble zNear , GLdouble zFar ) ;
 * </pre> 
 */
	public void gluPerspective (
		double fovy,
		double aspect,
		double zNear,
		double zFar
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluPickMatrix ( GLdouble x , GLdouble y , GLdouble delX , GLdouble delY , GLint * viewport ) ;
 * </pre> 
 */
	public void gluPickMatrix (
		double x,
		double y,
		double delX,
		double delY,
		int[] viewport
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern GLint gluProject ( GLdouble objX , GLdouble objY , GLdouble objZ , const GLdouble * model , const GLdouble * proj , const GLint * view , GLdouble * winX , GLdouble * winY , GLdouble * winZ ) ;
 * </pre> 
 */
	public int gluProject (
		double objX,
		double objY,
		double objZ,
		double[] model,
		double[] proj,
		int[] view,
		double[] winX,
		double[] winY,
		double[] winZ
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluPwlCurve ( GLUnurbs * nurb , GLint count , GLfloat * data , GLint stride , GLenum type ) ;
 * </pre> 
 */
	public void gluPwlCurve (
		long nurb,
		int count,
		float[] data,
		int stride,
		int type
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluQuadricDrawStyle ( GLUquadric * quad , GLenum draw ) ;
 * </pre> 
 */
	public void gluQuadricDrawStyle (
		long quad,
		int draw
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluQuadricNormals ( GLUquadric * quad , GLenum normal ) ;
 * </pre> 
 */
	public void gluQuadricNormals (
		long quad,
		int normal
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluQuadricOrientation ( GLUquadric * quad , GLenum orientation ) ;
 * </pre> 
 */
	public void gluQuadricOrientation (
		long quad,
		int orientation
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluQuadricTexture ( GLUquadric * quad , GLboolean texture ) ;
 * </pre> 
 */
	public void gluQuadricTexture (
		long quad,
		boolean texture
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern GLint gluScaleImage ( GLenum format , GLsizei wIn , GLsizei hIn , GLenum typeIn , const void * dataIn , GLsizei wOut , GLsizei hOut , GLenum typeOut , GLvoid * dataOut ) ;
 * </pre> 
 */
	public int gluScaleImage (
		int format,
		int wIn,
		int hIn,
		int typeIn,
		byte[] dataIn,
		int wOut,
		int hOut,
		int typeOut,
		byte[] dataOut
	) ;
	public int gluScaleImage (
		int format,
		int wIn,
		int hIn,
		int typeIn,
		short[] dataIn,
		int wOut,
		int hOut,
		int typeOut,
		short[] dataOut
	) ;
	public int gluScaleImage (
		int format,
		int wIn,
		int hIn,
		int typeIn,
		int[] dataIn,
		int wOut,
		int hOut,
		int typeOut,
		int[] dataOut
	) ;
	public int gluScaleImage (
		int format,
		int wIn,
		int hIn,
		int typeIn,
		float[] dataIn,
		int wOut,
		int hOut,
		int typeOut,
		float[] dataOut
	) ;
	public int gluScaleImage (
		int format,
		int wIn,
		int hIn,
		int typeIn,
		double[] dataIn,
		int wOut,
		int hOut,
		int typeOut,
		double[] dataOut
	) ;
	public int gluScaleImage (
		int format,
		int wIn,
		int hIn,
		int typeIn,
		boolean[] dataIn,
		int wOut,
		int hOut,
		int typeOut,
		boolean[] dataOut
	) ;
	public int gluScaleImage (
		int format,
		int wIn,
		int hIn,
		int typeIn,
		long[] dataIn,
		int wOut,
		int hOut,
		int typeOut,
		long[] dataOut
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluSphere ( GLUquadric * quad , GLdouble radius , GLint slices , GLint stacks ) ;
 * </pre> 
 */
	public void gluSphere (
		long quad,
		double radius,
		int slices,
		int stacks
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluTessBeginContour ( GLUtesselator * tess ) ;
 * </pre> 
 */
	public void gluTessBeginContour (
		long tess
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluTessBeginPolygon ( GLUtesselator * tess , GLvoid * data ) ;
 * </pre> 
 */
	public void gluTessBeginPolygon (
		long tess,
		byte[] data
	) ;
	public void gluTessBeginPolygon (
		long tess,
		short[] data
	) ;
	public void gluTessBeginPolygon (
		long tess,
		int[] data
	) ;
	public void gluTessBeginPolygon (
		long tess,
		float[] data
	) ;
	public void gluTessBeginPolygon (
		long tess,
		double[] data
	) ;
	public void gluTessBeginPolygon (
		long tess,
		boolean[] data
	) ;
	public void gluTessBeginPolygon (
		long tess,
		long[] data
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluTessEndContour ( GLUtesselator * tess ) ;
 * </pre> 
 */
	public void gluTessEndContour (
		long tess
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluTessEndPolygon ( GLUtesselator * tess ) ;
 * </pre> 
 */
	public void gluTessEndPolygon (
		long tess
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluTessNormal ( GLUtesselator * tess , GLdouble valueX , GLdouble valueY , GLdouble valueZ ) ;
 * </pre> 
 */
	public void gluTessNormal (
		long tess,
		double valueX,
		double valueY,
		double valueZ
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluTessProperty ( GLUtesselator * tess , GLenum which , GLdouble data ) ;
 * </pre> 
 */
	public void gluTessProperty (
		long tess,
		int which,
		double data
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluTessVertex ( GLUtesselator * tess , GLdouble * location , GLvoid * data ) ;
 * </pre> 
 */
	public void gluTessVertex (
		long tess,
		double[] location,
		byte[] data
	) ;
	public void gluTessVertex (
		long tess,
		double[] location,
		short[] data
	) ;
	public void gluTessVertex (
		long tess,
		double[] location,
		int[] data
	) ;
	public void gluTessVertex (
		long tess,
		double[] location,
		float[] data
	) ;
	public void gluTessVertex (
		long tess,
		double[] location,
		double[] data
	) ;
	public void gluTessVertex (
		long tess,
		double[] location,
		boolean[] data
	) ;
	public void gluTessVertex (
		long tess,
		double[] location,
		long[] data
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern GLint gluUnProject ( GLdouble winX , GLdouble winY , GLdouble winZ , const GLdouble * model , const GLdouble * proj , const GLint * view , GLdouble * objX , GLdouble * objY , GLdouble * objZ ) ;
 * </pre> 
 */
	public int gluUnProject (
		double winX,
		double winY,
		double winZ,
		double[] model,
		double[] proj,
		int[] view,
		double[] objX,
		double[] objY,
		double[] objZ
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern GLint gluUnProject4 ( GLdouble winX , GLdouble winY , GLdouble winZ , GLdouble clipW , const GLdouble * model , const GLdouble * proj , const GLint * view , GLdouble nearVal , GLdouble farVal , GLdouble * objX , GLdouble * objY , GLdouble * objZ , GLdouble * objW ) ;
 * </pre> 
 */
	public int gluUnProject4 (
		double winX,
		double winY,
		double winZ,
		double clipW,
		double[] model,
		double[] proj,
		int[] view,
		double nearVal,
		double farVal,
		double[] objX,
		double[] objY,
		double[] objZ,
		double[] objW
	) ;

/* C2J Parser Version 3.0:  Java program parsed successfully. */ 


}

