/* WARNING ! WARNING *** THIS FILE IS GENERATED BY C2J !!!

   DO NOT MAKE ANY CHANGES *** MAKE CHANGES IN THE SKELETON FILES !!!
*/


/**
 * @(#) GLUFuncJauJNI.java
 */


package gl4java;

/**
 * The default implementation class for GLU native function mapping
 *
 * @version 	2.00, 21. April 1999
 * @author      Sven Goethel
 */
public class GLUFuncJauJNI 
	implements GLUFunc 
{


public final native String gluErrorString ( int errorCode ) ;
public final native String gluGetString ( int name ) ;

public final native String getNativeVendor ( ) ;
public final native String getNativeVersion ( ) ;

public final String getClassVendor ( ) 
{ return "Jausoft - Sven Goethel Software Development"; }

public final String getClassVersion ( ) 
{ return "2.8.1.0"; }


/**
 * The Callback registry function.
 * To achieve the signature (internal argument signature)
 * you can use the "javap -s <classname>" toolkit of the JDK !
 *
 * @param qobj	the quadratic id, fetch with gluNewQuadric
 * @param which the id for the callback type
 * @param methodClassInstance the class instance,
 *                            which implements the callback-method
 * @param methodName  the name of the callback-method
 * @param signature  the signature of the callback-method.
 *
 * @see GLUFunc#gluNewQuadric
 */
public final native void  gluQuadricCallback(
                                  long qobj, int which,
			          Object methodClassInstance, 
				  String methodName, 
				  String signature
				  );

/**
 * The Callback registry function.
 * To achieve the signature (internal argument signature)
 * you can use the "javap -s <classname>" toolkit of the JDK !
 *
 * @param nobj	the nurbs id, fetch with gluNewNurbsRenderer
 * @param which the id for the callback type
 * @param methodClassInstance the class instance,
 *                            which implements the callback-method
 * @param methodName  the name of the callback-method
 * @param signature  the signature of the callback-method.
 *
 * @see GLUFunc#gluNewNurbsRenderer
 */
public final native void  gluNurbsCallback(
			          long nobj, int which,
			          Object methodClassInstance, 
			          String methodName, 
				  String signature
				  );


/**
extern void  gluNurbsCallbackData (GLUnurbs* nurb, GLvoid* userData);
extern void  gluNurbsCallbackDataEXT (GLUnurbs* nurb, GLvoid* userData);
**/

/**
 * The Callback registry function.
 * To achieve the signature (internal argument signature)
 * you can use the "javap -s <classname>" toolkit of the JDK !
 *
 * @param tobj	the tesselation id, fetch with gluNewTess
 * @param which the id for the callback type
 * @param methodClassInstance the class instance,
 *                            which implements the callback-method
 * @param methodName  the name of the callback-method
 * @param signature  the signature of the callback-method.
 * @param voidArrayLen1 the optional length of the 1st array
 *                      in the callback-methods argument-list
 * @param voidArrayLen2 the optional length of the 2nd array
 *                      in the callback-methods argument-list
 * @param voidArrayLen3 the optional length of the 3rd array
 *                      in the callback-methods argument-list
 * @param voidArrayLen4 the optional length of the 4th array
 *                      in the callback-methods argument-list
 * @param voidArrayLen5 the optional length of the 5th array
 *                      in the callback-methods argument-list
 *
 * @see GLUFunc#gluNewTess
 */
public final native void  gluTessCallback(
				  long tobj, int which,
			          Object methodClassInstance, 
			          String methodName, 
				  String signature,
				  int voidArrayLen1,
				  int voidArrayLen2,
				  int voidArrayLen3,
				  int voidArrayLen4,
				  int voidArrayLen5
				  );

/**
 * The Callback de-registry function.
 *
 * @param qobj	the quadratic id, for which all callback-methods
 *              should be de-registered
 */
public final native void  gluDeleteQuadric( long qobj );

/**
 * The Callback de-registry function.
 *
 * @param nobj	the nurbs id, for which all callback-methods
 *              should be de-registered
 */
public final native void  gluDeleteNurbsRenderer( long nobj );

/**
 * The Callback de-registry function.
 *
 * @param tobj	the tesselation id, for which all callback-methods
 *              should be de-registered
 */
public final native void  gluDeleteTess( long tobj );

public final native long  gluNewQuadric( );
public final native long  gluNewNurbsRenderer( );
public final native long  gluNewTess( );

/**
 * Wrapper for original gluProject,
 * where the orig. last three arguments are wrapped 
 * mapped in one array: (winx[1], winy[1], winz[1]) <-> win[3]
 *
 * @param obj array of the three obj x,y,z input components
 * @param win array of the three win x,y,z output components
 * @see gl4java.GLUFunc#gluProject
 */
public final int gluProject(double obj[],
                            double[] modelMatrix,
                            double[] projMatrix,
                            int[] viewport,
                            double[] win)
{
	return gluProject( obj[0], obj[1], obj[2],
			   modelMatrix, projMatrix, viewport, win);
}

/**
 * Wrapper for original gluProject,
 * where the orig. last three arguments are wrapped 
 * mapped in one array: (winx[1], winy[1], winz[1]) <-> win[3]
 *
 * @param win array of the three win x,y,z output components
 * @see gl4java.GLUFunc#gluProject
 */
public final int gluProject(double objx,
                            double objy,
                            double objz,
                            double[] modelMatrix,
                            double[] projMatrix,
                            int[] viewport,
                            double[] win)
{
	double x[] = { 0 };
	double y[] = { 0 };
	double z[] = { 0 };

	int r = gluProject(objx, objy, objz, modelMatrix, projMatrix,
                             viewport, x, y, z);

	if(win!=null && win.length>=3)
	{
		win[0]=x[0]; win[1]=y[0]; win[2]=z[0];
	}

	return r;
}

/**
 * Wrapper for original gluUnProject,
 * where the orig. last three arguments are wrapped 
 * mapped in one array: (objx[1], objy[1], objz[1]) <-> obj[3]
 *
 * @param win array of the three win x,y,z input components
 * @param obj array of the three obj x,y,z output components
 * @see gl4java.GLUFunc#gluUnProject
 */
public final int gluUnProject(double win[],
                              double[] modelMatrix,
                              double[] projMatrix,
                              int[] viewport,
                              double[] obj)
{
	return gluUnProject(win[0], win[1], win[2],
                            modelMatrix, projMatrix, viewport, obj);
}

/**
 * Wrapper for original gluUnProject,
 * where the orig. last three arguments are wrapped 
 * mapped in one array: (objx[1], objy[1], objz[1]) <-> obj[3]
 *
 * @param obj array of the three obj x,y,z output components
 * @see gl4java.GLUFunc#gluUnProject
 */
public final int gluUnProject(double winx,
                              double winy,
                              double winz,
                              double[] modelMatrix,
                              double[] projMatrix,
                              int[] viewport,
                              double[] obj)
{
	double x[] = { 0 };
	double y[] = { 0 };
	double z[] = { 0 };

	int r = gluUnProject(winx, winy, winz, modelMatrix, projMatrix,
                             viewport, x, y, z);

	if(obj!=null && obj.length>=3)
	{
		obj[0]=x[0]; obj[1]=y[0]; obj[2]=z[0];
	}

	return r;
}

/**
 * C2J Parser Version 3.0
 * Jausoft - Sven Goethel Software Development
 * Reading from file: glu-proto-auto.orig.h . . .
 * Destination-Class: gl4java_GLUFuncJauJNI ! 
 */

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluBeginCurve ( GLUnurbs * nurb ) ;
 * </pre> 
 */
	public final native void gluBeginCurve (
		long nurb
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluBeginPolygon ( GLUtesselator * tess ) ;
 * </pre> 
 */
	public final native void gluBeginPolygon (
		long tess
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluBeginSurface ( GLUnurbs * nurb ) ;
 * </pre> 
 */
	public final native void gluBeginSurface (
		long nurb
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluBeginTrim ( GLUnurbs * nurb ) ;
 * </pre> 
 */
	public final native void gluBeginTrim (
		long nurb
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern GLint gluBuild1DMipmapLevels ( GLenum target , GLint internalFormat , GLsizei width , GLenum format , GLenum type , GLint level , GLint base , GLint max , const void * data ) ;
 * </pre> 
 */
	public final native int gluBuild1DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int format,
		int type,
		int level,
		int base,
		int max,
		byte[] data
	) ;
	public final native int gluBuild1DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int format,
		int type,
		int level,
		int base,
		int max,
		short[] data
	) ;
	public final native int gluBuild1DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int format,
		int type,
		int level,
		int base,
		int max,
		int[] data
	) ;
	public final native int gluBuild1DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int format,
		int type,
		int level,
		int base,
		int max,
		float[] data
	) ;
	public final native int gluBuild1DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int format,
		int type,
		int level,
		int base,
		int max,
		double[] data
	) ;
	public final native int gluBuild1DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int format,
		int type,
		int level,
		int base,
		int max,
		boolean[] data
	) ;
	public final native int gluBuild1DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int format,
		int type,
		int level,
		int base,
		int max,
		long[] data
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern GLint gluBuild1DMipmaps ( GLenum target , GLint internalFormat , GLsizei width , GLenum format , GLenum type , const void * data ) ;
 * </pre> 
 */
	public final native int gluBuild1DMipmaps (
		int target,
		int internalFormat,
		int width,
		int format,
		int type,
		byte[] data
	) ;
	public final native int gluBuild1DMipmaps (
		int target,
		int internalFormat,
		int width,
		int format,
		int type,
		short[] data
	) ;
	public final native int gluBuild1DMipmaps (
		int target,
		int internalFormat,
		int width,
		int format,
		int type,
		int[] data
	) ;
	public final native int gluBuild1DMipmaps (
		int target,
		int internalFormat,
		int width,
		int format,
		int type,
		float[] data
	) ;
	public final native int gluBuild1DMipmaps (
		int target,
		int internalFormat,
		int width,
		int format,
		int type,
		double[] data
	) ;
	public final native int gluBuild1DMipmaps (
		int target,
		int internalFormat,
		int width,
		int format,
		int type,
		boolean[] data
	) ;
	public final native int gluBuild1DMipmaps (
		int target,
		int internalFormat,
		int width,
		int format,
		int type,
		long[] data
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern GLint gluBuild2DMipmapLevels ( GLenum target , GLint internalFormat , GLsizei width , GLsizei height , GLenum format , GLenum type , GLint level , GLint base , GLint max , const void * data ) ;
 * </pre> 
 */
	public final native int gluBuild2DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int height,
		int format,
		int type,
		int level,
		int base,
		int max,
		byte[] data
	) ;
	public final native int gluBuild2DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int height,
		int format,
		int type,
		int level,
		int base,
		int max,
		short[] data
	) ;
	public final native int gluBuild2DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int height,
		int format,
		int type,
		int level,
		int base,
		int max,
		int[] data
	) ;
	public final native int gluBuild2DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int height,
		int format,
		int type,
		int level,
		int base,
		int max,
		float[] data
	) ;
	public final native int gluBuild2DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int height,
		int format,
		int type,
		int level,
		int base,
		int max,
		double[] data
	) ;
	public final native int gluBuild2DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int height,
		int format,
		int type,
		int level,
		int base,
		int max,
		boolean[] data
	) ;
	public final native int gluBuild2DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int height,
		int format,
		int type,
		int level,
		int base,
		int max,
		long[] data
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern GLint gluBuild2DMipmaps ( GLenum target , GLint internalFormat , GLsizei width , GLsizei height , GLenum format , GLenum type , const void * data ) ;
 * </pre> 
 */
	public final native int gluBuild2DMipmaps (
		int target,
		int internalFormat,
		int width,
		int height,
		int format,
		int type,
		byte[] data
	) ;
	public final native int gluBuild2DMipmaps (
		int target,
		int internalFormat,
		int width,
		int height,
		int format,
		int type,
		short[] data
	) ;
	public final native int gluBuild2DMipmaps (
		int target,
		int internalFormat,
		int width,
		int height,
		int format,
		int type,
		int[] data
	) ;
	public final native int gluBuild2DMipmaps (
		int target,
		int internalFormat,
		int width,
		int height,
		int format,
		int type,
		float[] data
	) ;
	public final native int gluBuild2DMipmaps (
		int target,
		int internalFormat,
		int width,
		int height,
		int format,
		int type,
		double[] data
	) ;
	public final native int gluBuild2DMipmaps (
		int target,
		int internalFormat,
		int width,
		int height,
		int format,
		int type,
		boolean[] data
	) ;
	public final native int gluBuild2DMipmaps (
		int target,
		int internalFormat,
		int width,
		int height,
		int format,
		int type,
		long[] data
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern GLint gluBuild3DMipmapLevels ( GLenum target , GLint internalFormat , GLsizei width , GLsizei height , GLsizei depth , GLenum format , GLenum type , GLint level , GLint base , GLint max , const void * data ) ;
 * </pre> 
 */
	public final native int gluBuild3DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int height,
		int depth,
		int format,
		int type,
		int level,
		int base,
		int max,
		byte[] data
	) ;
	public final native int gluBuild3DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int height,
		int depth,
		int format,
		int type,
		int level,
		int base,
		int max,
		short[] data
	) ;
	public final native int gluBuild3DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int height,
		int depth,
		int format,
		int type,
		int level,
		int base,
		int max,
		int[] data
	) ;
	public final native int gluBuild3DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int height,
		int depth,
		int format,
		int type,
		int level,
		int base,
		int max,
		float[] data
	) ;
	public final native int gluBuild3DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int height,
		int depth,
		int format,
		int type,
		int level,
		int base,
		int max,
		double[] data
	) ;
	public final native int gluBuild3DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int height,
		int depth,
		int format,
		int type,
		int level,
		int base,
		int max,
		boolean[] data
	) ;
	public final native int gluBuild3DMipmapLevels (
		int target,
		int internalFormat,
		int width,
		int height,
		int depth,
		int format,
		int type,
		int level,
		int base,
		int max,
		long[] data
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern GLint gluBuild3DMipmaps ( GLenum target , GLint internalFormat , GLsizei width , GLsizei height , GLsizei depth , GLenum format , GLenum type , const void * data ) ;
 * </pre> 
 */
	public final native int gluBuild3DMipmaps (
		int target,
		int internalFormat,
		int width,
		int height,
		int depth,
		int format,
		int type,
		byte[] data
	) ;
	public final native int gluBuild3DMipmaps (
		int target,
		int internalFormat,
		int width,
		int height,
		int depth,
		int format,
		int type,
		short[] data
	) ;
	public final native int gluBuild3DMipmaps (
		int target,
		int internalFormat,
		int width,
		int height,
		int depth,
		int format,
		int type,
		int[] data
	) ;
	public final native int gluBuild3DMipmaps (
		int target,
		int internalFormat,
		int width,
		int height,
		int depth,
		int format,
		int type,
		float[] data
	) ;
	public final native int gluBuild3DMipmaps (
		int target,
		int internalFormat,
		int width,
		int height,
		int depth,
		int format,
		int type,
		double[] data
	) ;
	public final native int gluBuild3DMipmaps (
		int target,
		int internalFormat,
		int width,
		int height,
		int depth,
		int format,
		int type,
		boolean[] data
	) ;
	public final native int gluBuild3DMipmaps (
		int target,
		int internalFormat,
		int width,
		int height,
		int depth,
		int format,
		int type,
		long[] data
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern GLboolean gluCheckExtension ( const GLubyte * extName , const GLubyte * extString ) ;
 * </pre> 
 */
	public final native boolean gluCheckExtension (
		byte[] extName,
		byte[] extString
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluCylinder ( GLUquadric * quad , GLdouble base , GLdouble top , GLdouble height , GLint slices , GLint stacks ) ;
 * </pre> 
 */
	public final native void gluCylinder (
		long quad,
		double base,
		double top,
		double height,
		int slices,
		int stacks
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluDisk ( GLUquadric * quad , GLdouble inner , GLdouble outer , GLint slices , GLint loops ) ;
 * </pre> 
 */
	public final native void gluDisk (
		long quad,
		double inner,
		double outer,
		int slices,
		int loops
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluEndCurve ( GLUnurbs * nurb ) ;
 * </pre> 
 */
	public final native void gluEndCurve (
		long nurb
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluEndPolygon ( GLUtesselator * tess ) ;
 * </pre> 
 */
	public final native void gluEndPolygon (
		long tess
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluEndSurface ( GLUnurbs * nurb ) ;
 * </pre> 
 */
	public final native void gluEndSurface (
		long nurb
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluEndTrim ( GLUnurbs * nurb ) ;
 * </pre> 
 */
	public final native void gluEndTrim (
		long nurb
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluGetNurbsProperty ( GLUnurbs * nurb , GLenum property , GLfloat * data ) ;
 * </pre> 
 */
	public final native void gluGetNurbsProperty (
		long nurb,
		int property,
		float[] data
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluGetTessProperty ( GLUtesselator * tess , GLenum which , GLdouble * data ) ;
 * </pre> 
 */
	public final native void gluGetTessProperty (
		long tess,
		int which,
		double[] data
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluLoadSamplingMatrices ( GLUnurbs * nurb , const GLfloat * model , const GLfloat * perspective , const GLint * view ) ;
 * </pre> 
 */
	public final native void gluLoadSamplingMatrices (
		long nurb,
		float[] model,
		float[] perspective,
		int[] view
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluLookAt ( GLdouble eyeX , GLdouble eyeY , GLdouble eyeZ , GLdouble centerX , GLdouble centerY , GLdouble centerZ , GLdouble upX , GLdouble upY , GLdouble upZ ) ;
 * </pre> 
 */
	public final native void gluLookAt (
		double eyeX,
		double eyeY,
		double eyeZ,
		double centerX,
		double centerY,
		double centerZ,
		double upX,
		double upY,
		double upZ
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluNextContour ( GLUtesselator * tess , GLenum type ) ;
 * </pre> 
 */
	public final native void gluNextContour (
		long tess,
		int type
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluNurbsCurve ( GLUnurbs * nurb , GLint knotCount , GLfloat * knots , GLint stride , GLfloat * control , GLint order , GLenum type ) ;
 * </pre> 
 */
	public final native void gluNurbsCurve (
		long nurb,
		int knotCount,
		float[] knots,
		int stride,
		float[] control,
		int order,
		int type
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluNurbsProperty ( GLUnurbs * nurb , GLenum property , GLfloat value ) ;
 * </pre> 
 */
	public final native void gluNurbsProperty (
		long nurb,
		int property,
		float value
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluNurbsSurface ( GLUnurbs * nurb , GLint sKnotCount , GLfloat * sKnots , GLint tKnotCount , GLfloat * tKnots , GLint sStride , GLint tStride , GLfloat * control , GLint sOrder , GLint tOrder , GLenum type ) ;
 * </pre> 
 */
	public final native void gluNurbsSurface (
		long nurb,
		int sKnotCount,
		float[] sKnots,
		int tKnotCount,
		float[] tKnots,
		int sStride,
		int tStride,
		float[] control,
		int sOrder,
		int tOrder,
		int type
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluOrtho2D ( GLdouble left , GLdouble right , GLdouble bottom , GLdouble top ) ;
 * </pre> 
 */
	public final native void gluOrtho2D (
		double left,
		double right,
		double bottom,
		double top
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluPartialDisk ( GLUquadric * quad , GLdouble inner , GLdouble outer , GLint slices , GLint loops , GLdouble start , GLdouble sweep ) ;
 * </pre> 
 */
	public final native void gluPartialDisk (
		long quad,
		double inner,
		double outer,
		int slices,
		int loops,
		double start,
		double sweep
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluPerspective ( GLdouble fovy , GLdouble aspect , GLdouble zNear , GLdouble zFar ) ;
 * </pre> 
 */
	public final native void gluPerspective (
		double fovy,
		double aspect,
		double zNear,
		double zFar
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluPickMatrix ( GLdouble x , GLdouble y , GLdouble delX , GLdouble delY , GLint * viewport ) ;
 * </pre> 
 */
	public final native void gluPickMatrix (
		double x,
		double y,
		double delX,
		double delY,
		int[] viewport
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern GLint gluProject ( GLdouble objX , GLdouble objY , GLdouble objZ , const GLdouble * model , const GLdouble * proj , const GLint * view , GLdouble * winX , GLdouble * winY , GLdouble * winZ ) ;
 * </pre> 
 */
	public final native int gluProject (
		double objX,
		double objY,
		double objZ,
		double[] model,
		double[] proj,
		int[] view,
		double[] winX,
		double[] winY,
		double[] winZ
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluPwlCurve ( GLUnurbs * nurb , GLint count , GLfloat * data , GLint stride , GLenum type ) ;
 * </pre> 
 */
	public final native void gluPwlCurve (
		long nurb,
		int count,
		float[] data,
		int stride,
		int type
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluQuadricDrawStyle ( GLUquadric * quad , GLenum draw ) ;
 * </pre> 
 */
	public final native void gluQuadricDrawStyle (
		long quad,
		int draw
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluQuadricNormals ( GLUquadric * quad , GLenum normal ) ;
 * </pre> 
 */
	public final native void gluQuadricNormals (
		long quad,
		int normal
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluQuadricOrientation ( GLUquadric * quad , GLenum orientation ) ;
 * </pre> 
 */
	public final native void gluQuadricOrientation (
		long quad,
		int orientation
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluQuadricTexture ( GLUquadric * quad , GLboolean texture ) ;
 * </pre> 
 */
	public final native void gluQuadricTexture (
		long quad,
		boolean texture
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern GLint gluScaleImage ( GLenum format , GLsizei wIn , GLsizei hIn , GLenum typeIn , const void * dataIn , GLsizei wOut , GLsizei hOut , GLenum typeOut , GLvoid * dataOut ) ;
 * </pre> 
 */
	public final native int gluScaleImage (
		int format,
		int wIn,
		int hIn,
		int typeIn,
		byte[] dataIn,
		int wOut,
		int hOut,
		int typeOut,
		byte[] dataOut
	) ;
	public final native int gluScaleImage (
		int format,
		int wIn,
		int hIn,
		int typeIn,
		short[] dataIn,
		int wOut,
		int hOut,
		int typeOut,
		short[] dataOut
	) ;
	public final native int gluScaleImage (
		int format,
		int wIn,
		int hIn,
		int typeIn,
		int[] dataIn,
		int wOut,
		int hOut,
		int typeOut,
		int[] dataOut
	) ;
	public final native int gluScaleImage (
		int format,
		int wIn,
		int hIn,
		int typeIn,
		float[] dataIn,
		int wOut,
		int hOut,
		int typeOut,
		float[] dataOut
	) ;
	public final native int gluScaleImage (
		int format,
		int wIn,
		int hIn,
		int typeIn,
		double[] dataIn,
		int wOut,
		int hOut,
		int typeOut,
		double[] dataOut
	) ;
	public final native int gluScaleImage (
		int format,
		int wIn,
		int hIn,
		int typeIn,
		boolean[] dataIn,
		int wOut,
		int hOut,
		int typeOut,
		boolean[] dataOut
	) ;
	public final native int gluScaleImage (
		int format,
		int wIn,
		int hIn,
		int typeIn,
		long[] dataIn,
		int wOut,
		int hOut,
		int typeOut,
		long[] dataOut
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluSphere ( GLUquadric * quad , GLdouble radius , GLint slices , GLint stacks ) ;
 * </pre> 
 */
	public final native void gluSphere (
		long quad,
		double radius,
		int slices,
		int stacks
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluTessBeginContour ( GLUtesselator * tess ) ;
 * </pre> 
 */
	public final native void gluTessBeginContour (
		long tess
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluTessBeginPolygon ( GLUtesselator * tess , GLvoid * data ) ;
 * </pre> 
 */
	public final native void gluTessBeginPolygon (
		long tess,
		byte[] data
	) ;
	public final native void gluTessBeginPolygon (
		long tess,
		short[] data
	) ;
	public final native void gluTessBeginPolygon (
		long tess,
		int[] data
	) ;
	public final native void gluTessBeginPolygon (
		long tess,
		float[] data
	) ;
	public final native void gluTessBeginPolygon (
		long tess,
		double[] data
	) ;
	public final native void gluTessBeginPolygon (
		long tess,
		boolean[] data
	) ;
	public final native void gluTessBeginPolygon (
		long tess,
		long[] data
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluTessEndContour ( GLUtesselator * tess ) ;
 * </pre> 
 */
	public final native void gluTessEndContour (
		long tess
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluTessEndPolygon ( GLUtesselator * tess ) ;
 * </pre> 
 */
	public final native void gluTessEndPolygon (
		long tess
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluTessNormal ( GLUtesselator * tess , GLdouble valueX , GLdouble valueY , GLdouble valueZ ) ;
 * </pre> 
 */
	public final native void gluTessNormal (
		long tess,
		double valueX,
		double valueY,
		double valueZ
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluTessProperty ( GLUtesselator * tess , GLenum which , GLdouble data ) ;
 * </pre> 
 */
	public final native void gluTessProperty (
		long tess,
		int which,
		double data
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern void gluTessVertex ( GLUtesselator * tess , GLdouble * location , GLvoid * data ) ;
 * </pre> 
 */
	public final native void gluTessVertex (
		long tess,
		double[] location,
		byte[] data
	) ;
	public final native void gluTessVertex (
		long tess,
		double[] location,
		short[] data
	) ;
	public final native void gluTessVertex (
		long tess,
		double[] location,
		int[] data
	) ;
	public final native void gluTessVertex (
		long tess,
		double[] location,
		float[] data
	) ;
	public final native void gluTessVertex (
		long tess,
		double[] location,
		double[] data
	) ;
	public final native void gluTessVertex (
		long tess,
		double[] location,
		boolean[] data
	) ;
	public final native void gluTessVertex (
		long tess,
		double[] location,
		long[] data
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern GLint gluUnProject ( GLdouble winX , GLdouble winY , GLdouble winZ , const GLdouble * model , const GLdouble * proj , const GLint * view , GLdouble * objX , GLdouble * objY , GLdouble * objZ ) ;
 * </pre> 
 */
	public final native int gluUnProject (
		double winX,
		double winY,
		double winZ,
		double[] model,
		double[] proj,
		int[] view,
		double[] objX,
		double[] objY,
		double[] objZ
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   extern GLint gluUnProject4 ( GLdouble winX , GLdouble winY , GLdouble winZ , GLdouble clipW , const GLdouble * model , const GLdouble * proj , const GLint * view , GLdouble nearVal , GLdouble farVal , GLdouble * objX , GLdouble * objY , GLdouble * objZ , GLdouble * objW ) ;
 * </pre> 
 */
	public final native int gluUnProject4 (
		double winX,
		double winY,
		double winZ,
		double clipW,
		double[] model,
		double[] proj,
		int[] view,
		double nearVal,
		double farVal,
		double[] objX,
		double[] objY,
		double[] objZ,
		double[] objW
	) ;

/* C2J Parser Version 3.0:  Java program parsed successfully. */ 


}

