/**
 * @(#) GLFunc14.java
 */


package gl4java;

import java.nio.*;

/**
 * The base interface for OpenGL native function mapping
 *
 * @version 	2.00, 21. April 1999
 * @author      Sven Goethel
 */
public interface GLFunc14
	extends GLFunc 
{

  //----------------------------------------------------------------------
  // Special-case routines requiring hand coding
  //

  /** Access to the underlying wglAllocateMemoryNV or
      glXAllocateMemoryNV routine, if present. Presence of this
      routine can be queried by calling GLContext.gljTestGLProc with
      the argument "glAllocateMemoryNV". */
  public ByteBuffer glAllocateMemoryNV(int size,
                                       float readFreq,
                                       float writeFreq,
                                       float priority);

  //----------------------------------------------------------------------
  // All other routines below are autogenerated
  //

