/* WARNING ! WARNING *** THIS FILE IS GENERATED BY C2J !!!

   DO NOT MAKE ANY CHANGES *** MAKE CHANGES IN THE SKELETON FILES !!!
*/


/**
 * @(#) GLFFuncJNI.java
 */


package gl4java.utils.glf;

import java.net.*;

/**
 * The default implementation class for GLF native function mapping
 *
 * @version 	2.00, 21. April 1999
 * @author      Sven Goethel
 */
public abstract class GLFFuncJNI 
	implements GLFEnum
{

public abstract int glfLoadFont ( String fontname );

public abstract int glfLoadFont ( URL baseURL, String fontURI );

public abstract int glfLoadBFont ( String fontname );

public abstract int glfLoadBFont ( URL baseURL, String fontURI );

public final native String getNativeVendor ( ) ;
public final native String getNativeVersion ( ) ;

public final String getClassVendor ( ) 
{ return "Jausoft - Sven Goethel Software Development"; }

public final String getClassVersion ( ) 
{ return "1.4.0.0"; }

/**
 * Load Vector font to memory, by (FILE *) fontf 
 */
protected final native int glfLoadFontNative (long fontf);

/**
 * Load Bitmap font to memory, by (FILE *) fontf
 */
protected final native int glfLoadBFontNative (long fontf);

/**
 * C2J Parser Version 2.2
 * Jausoft - Sven Goethel Software Development
 * Reading from file: glf-proto-auto.orig.h . . .
 * Destination-Class: gl4java_utils_glf_GLF ! 
 */

/**
 * Original Function-Prototype :
 * <pre> 
   void glfInit ( ) ;
 * </pre> 
 */
	public final native void glfInit (
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfClose ( ) ;
 * </pre> 
 */
	public final native void glfClose (
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   int glfUnloadFont ( ) ;
 * </pre> 
 */
	public final native int glfUnloadFont (
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   int glfUnloadBFont ( ) ;
 * </pre> 
 */
	public final native int glfUnloadBFont (
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   int glfUnloadFontD ( int font_descriptor ) ;
 * </pre> 
 */
	public final native int glfUnloadFontD (
		int font_descriptor
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   int glfUnloadBFontD ( int bmf_descriptor ) ;
 * </pre> 
 */
	public final native int glfUnloadBFontD (
		int bmf_descriptor
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfDrawWiredSymbol ( char s ) ;
 * </pre> 
 */
	public final native void glfDrawWiredSymbol (
		byte s
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfDrawWiredString ( const char * s ) ;
 * </pre> 
 */
	public final native void glfDrawWiredString (
		String s
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfDrawSolidSymbol ( char s ) ;
 * </pre> 
 */
	public final native void glfDrawSolidSymbol (
		byte s
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfDrawSolidString ( const char * s ) ;
 * </pre> 
 */
	public final native void glfDrawSolidString (
		String s
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfDraw3DWiredSymbol ( char s ) ;
 * </pre> 
 */
	public final native void glfDraw3DWiredSymbol (
		byte s
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfDraw3DWiredString ( const char * s ) ;
 * </pre> 
 */
	public final native void glfDraw3DWiredString (
		String s
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfDraw3DSolidSymbol ( char s ) ;
 * </pre> 
 */
	public final native void glfDraw3DSolidSymbol (
		byte s
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfDraw3DSolidString ( const char * s ) ;
 * </pre> 
 */
	public final native void glfDraw3DSolidString (
		String s
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   int glfBeginBFont ( int Font_Descriptor ) ;
 * </pre> 
 */
	public final native int glfBeginBFont (
		int Font_Descriptor
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfEndBFont ( ) ;
 * </pre> 
 */
	public final native void glfEndBFont (
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfDrawBSymbol ( char s ) ;
 * </pre> 
 */
	public final native void glfDrawBSymbol (
		byte s
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfDrawBString ( const char * s ) ;
 * </pre> 
 */
	public final native void glfDrawBString (
		String s
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfDrawBMaskSymbol ( char s ) ;
 * </pre> 
 */
	public final native void glfDrawBMaskSymbol (
		byte s
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfDrawBMaskString ( const char * s ) ;
 * </pre> 
 */
	public final native void glfDrawBMaskString (
		String s
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfDrawWiredSymbolF ( int font_descriptor , char s ) ;
 * </pre> 
 */
	public final native void glfDrawWiredSymbolF (
		int font_descriptor,
		byte s
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfDrawWiredStringF ( int font_descriptor , const char * s ) ;
 * </pre> 
 */
	public final native void glfDrawWiredStringF (
		int font_descriptor,
		String s
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfDrawSolidSymbolF ( int font_descriptor , char s ) ;
 * </pre> 
 */
	public final native void glfDrawSolidSymbolF (
		int font_descriptor,
		byte s
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfDrawSolidStringF ( int font_descriptor , const char * s ) ;
 * </pre> 
 */
	public final native void glfDrawSolidStringF (
		int font_descriptor,
		String s
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfDraw3DWiredSymbolF ( int font_descriptor , char s ) ;
 * </pre> 
 */
	public final native void glfDraw3DWiredSymbolF (
		int font_descriptor,
		byte s
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfDraw3DWiredStringF ( int font_descriptor , const char * s ) ;
 * </pre> 
 */
	public final native void glfDraw3DWiredStringF (
		int font_descriptor,
		String s
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfDraw3DSolidSymbolF ( int font_descriptor , char s ) ;
 * </pre> 
 */
	public final native void glfDraw3DSolidSymbolF (
		int font_descriptor,
		byte s
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfDraw3DSolidStringF ( int font_descriptor , const char * s ) ;
 * </pre> 
 */
	public final native void glfDraw3DSolidStringF (
		int font_descriptor,
		String s
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfGetStringBoundsF ( int fd , const char * s , float * minx , float * miny , float * maxx , float * maxy ) ;
 * </pre> 
 */
	public final native void glfGetStringBoundsF (
		int fd,
		String s,
		float[] minx,
		float[] miny,
		float[] maxx,
		float[] maxy
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfGetStringBounds ( const char * s , float * minx , float * miny , float * maxx , float * maxy ) ;
 * </pre> 
 */
	public final native void glfGetStringBounds (
		String s,
		float[] minx,
		float[] miny,
		float[] maxx,
		float[] maxy
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfSetSymbolSpace ( float sp ) ;
 * </pre> 
 */
	public final native void glfSetSymbolSpace (
		float sp
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   float glfGetSymbolSpace ( ) ;
 * </pre> 
 */
	public final native float glfGetSymbolSpace (
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfSetSpaceSize ( float sp ) ;
 * </pre> 
 */
	public final native void glfSetSpaceSize (
		float sp
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   float glfGetSpaceSize ( ) ;
 * </pre> 
 */
	public final native float glfGetSpaceSize (
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfSetSymbolDepth ( float dpth ) ;
 * </pre> 
 */
	public final native void glfSetSymbolDepth (
		float dpth
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   float glfGetSymbolDepth ( ) ;
 * </pre> 
 */
	public final native float glfGetSymbolDepth (
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   int glfSetCurrentFont ( int Font_Descriptor ) ;
 * </pre> 
 */
	public final native int glfSetCurrentFont (
		int Font_Descriptor
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   int glfSetCurrentBFont ( int Font_Descriptor ) ;
 * </pre> 
 */
	public final native int glfSetCurrentBFont (
		int Font_Descriptor
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   int glfGetCurrentFont ( ) ;
 * </pre> 
 */
	public final native int glfGetCurrentFont (
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   int glfGetCurrentBFont ( ) ;
 * </pre> 
 */
	public final native int glfGetCurrentBFont (
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfSetAnchorPoint ( int anchp ) ;
 * </pre> 
 */
	public final native void glfSetAnchorPoint (
		int anchp
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfSetContourColor ( float r , float g , float b , float a ) ;
 * </pre> 
 */
	public final native void glfSetContourColor (
		float r,
		float g,
		float b,
		float a
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfEnable ( int what ) ;
 * </pre> 
 */
	public final native void glfEnable (
		int what
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfDisable ( int what ) ;
 * </pre> 
 */
	public final native void glfDisable (
		int what
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfSetConsoleParam ( int width , int height ) ;
 * </pre> 
 */
	public final native void glfSetConsoleParam (
		int width,
		int height
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   int glfSetConsoleFont ( int Font_Descriptor ) ;
 * </pre> 
 */
	public final native int glfSetConsoleFont (
		int Font_Descriptor
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfConsoleClear ( ) ;
 * </pre> 
 */
	public final native void glfConsoleClear (
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfPrint ( const char * s , int lenght ) ;
 * </pre> 
 */
	public final native void glfPrint (
		String s,
		int lenght
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfPrintString ( const char * s ) ;
 * </pre> 
 */
	public final native void glfPrintString (
		String s
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfPrintChar ( char s ) ;
 * </pre> 
 */
	public final native void glfPrintChar (
		byte s
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfConsoleDraw ( ) ;
 * </pre> 
 */
	public final native void glfConsoleDraw (
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfSetCursorBlinkRate ( int Rate ) ;
 * </pre> 
 */
	public final native void glfSetCursorBlinkRate (
		int Rate
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfStringCentering ( GLboolean center ) ;
 * </pre> 
 */
	public final native void glfStringCentering (
		boolean center
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   GLboolean glfGetStringCentering ( ) ;
 * </pre> 
 */
	public final native boolean glfGetStringCentering (
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfBitmapStringCentering ( GLboolean center ) ;
 * </pre> 
 */
	public final native void glfBitmapStringCentering (
		boolean center
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   GLboolean glfBitmapGetStringCentering ( ) ;
 * </pre> 
 */
	public final native boolean glfBitmapGetStringCentering (
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfStringDirection ( GLuint direction ) ;
 * </pre> 
 */
	public final native void glfStringDirection (
		int direction
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   GLuint glfGetStringDirection ( ) ;
 * </pre> 
 */
	public final native int glfGetStringDirection (
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfSetRotateAngle ( float angle ) ;
 * </pre> 
 */
	public final native void glfSetRotateAngle (
		float angle
	) ;

/**
 * Original Function-Prototype :
 * <pre> 
   void glfSetBRotateAngle ( float angle ) ;
 * </pre> 
 */
	public final native void glfSetBRotateAngle (
		float angle
	) ;

/* C2J Parser Version 2.2:  Java program parsed successfully. */ 


}

