/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tess */

#ifndef _Included_tess
#define _Included_tess
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: LOCK */
#undef tess_assert
#define tess_assert 0L
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef tess_TOP_ALIGNMENT
#define tess_TOP_ALIGNMENT 0.0f
#undef tess_CENTER_ALIGNMENT
#define tess_CENTER_ALIGNMENT 0.5f
#undef tess_BOTTOM_ALIGNMENT
#define tess_BOTTOM_ALIGNMENT 1.0f
#undef tess_LEFT_ALIGNMENT
#define tess_LEFT_ALIGNMENT 0.0f
#undef tess_RIGHT_ALIGNMENT
#define tess_RIGHT_ALIGNMENT 1.0f
#undef tess_serialVersionUID
#define tess_serialVersionUID -7644114512714619750LL
#undef tess_serialVersionUID
#define tess_serialVersionUID 4613797578919906343LL
/* Inaccessible static: nameCounter */
#undef tess_serialVersionUID
#define tess_serialVersionUID -2728009084054400034LL
#undef tess_serialVersionUID
#define tess_serialVersionUID -5836846270535785031LL
/* Inaccessible static: rect */
/* Inaccessible static: tri */
/* Inaccessible static: star */
#ifdef __cplusplus
}
#endif
#endif
