/* Generated By:JavaCC: Do not edit this line. C2JConstants.java */
public interface C2JConstants {

  int EOF = 0;
  int INTEGER_LITERAL = 7;
  int DECIMAL_LITERAL = 8;
  int HEX_LITERAL = 9;
  int OCTAL_LITERAL = 10;
  int FLOATING_POINT_LITERAL = 11;
  int EXPONENT = 12;
  int CHARACTER_LITERAL = 13;
  int STRING_LITERAL = 14;
  int CONTINUE = 15;
  int VOLATILE = 16;
  int REGISTER = 17;
  int UNSIGNED = 18;
  int TYPEDEF = 19;
  int DFLT = 20;
  int DOUBLE = 21;
  int SIZEOF = 22;
  int SWITCH = 23;
  int RETURN = 24;
  int EXTERN = 25;
  int STRUCT = 26;
  int STATIC = 27;
  int SIGNED = 28;
  int WHILE = 29;
  int BREAK = 30;
  int UNION = 31;
  int CONST = 32;
  int FLOAT = 33;
  int SHORT = 34;
  int ELSE = 35;
  int CASE = 36;
  int LONG = 37;
  int ENUM = 38;
  int AUTO = 39;
  int VOID = 40;
  int CHAR = 41;
  int GOTO = 42;
  int FOR = 43;
  int INT = 44;
  int IF = 45;
  int DO = 46;
  int GLvoid = 47;
  int GLbyte = 48;
  int GLshort = 49;
  int GLint = 50;
  int GLsizei = 51;
  int GLfloat = 52;
  int GLclampf = 53;
  int GLdouble = 54;
  int GLclampd = 55;
  int GLubyte = 56;
  int GLboolean = 57;
  int GLushort = 58;
  int GLuint = 59;
  int GLenum = 60;
  int GLbitfield = 61;
  int GLUquadric = 62;
  int GLUnurbs = 63;
  int GLUtesselator = 64;
  int GLUtriangulator = 65;
  int IDENTIFIER = 66;
  int LETTER = 67;
  int DIGIT = 68;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"continue\"",
    "\"volatile\"",
    "\"register\"",
    "\"unsigned\"",
    "\"typedef\"",
    "\"default\"",
    "\"double\"",
    "\"sizeof\"",
    "\"switch\"",
    "\"return\"",
    "\"extern\"",
    "\"struct\"",
    "\"static\"",
    "\"signed\"",
    "\"while\"",
    "\"break\"",
    "\"union\"",
    "\"const\"",
    "\"float\"",
    "\"short\"",
    "\"else\"",
    "\"case\"",
    "\"long\"",
    "\"enum\"",
    "\"auto\"",
    "\"void\"",
    "\"char\"",
    "\"goto\"",
    "\"for\"",
    "\"int\"",
    "\"if\"",
    "\"do\"",
    "\"GLvoid\"",
    "\"GLbyte\"",
    "\"GLshort\"",
    "\"GLint\"",
    "\"GLsizei\"",
    "\"GLfloat\"",
    "\"GLclampf\"",
    "\"GLdouble\"",
    "\"GLclampd\"",
    "\"GLubyte\"",
    "\"GLboolean\"",
    "\"GLushort\"",
    "\"GLuint\"",
    "\"GLenum\"",
    "\"GLbitfield\"",
    "\"GLUquadric\"",
    "\"GLUnurbs\"",
    "\"GLUtesselator\"",
    "\"GLUtriangulator\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"=\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"*\"",
    "\"...\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"+=\"",
    "\"-=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"&=\"",
    "\"^=\"",
    "\"|=\"",
    "\"?\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"<<\"",
    "\">>\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"%\"",
    "\"++\"",
    "\"--\"",
    "\"~\"",
    "\"!\"",
    "\".\"",
    "\"->\"",
  };

}
