
copy2jaulocal:
	cp -a *.txt *.html \
		~/projects/jausoft-httpd/Files/Java/1.1.X/GL4Java/Installer
	cp -a *.cab *.jar *.class *.crt *.policy \
		~/projects/jausoft-httpd/Files/Java/1.1.X/GL4Java/Installer
